### PR TITLE
WIP: possible changes to Traffic_redux

### PR DESCRIPTION
**Pull request by rjleveque**
I'm still going through this..

### CODE REVIEW

**Comment by rjleveque** [comment]
A couple things I noticed in `Traffic_variable_speed.ipynb`:

The annotation `t -->` that moves up the t-axis in some plots is interior to the plot instead of outside the plot, I think because we're not choosing its location well in `riemann_tools.plot_waves`:

```
    if t_pointer:
        ax.text(-1.8*xmax,t,'t = %4.2f -->' % t)
```

When the slider bar is moved to `t=0` it doesn't always show a nice discontinuity from `ql` to `qr` if the Riemann solution has values of `q` outside this range, instead there's a spike due to these lines in `riemann_tools.plot_riemann`:

```
    if t == 0:
        q = riemann_eval(x/1e-10)
    else:
        q = riemann_eval(x/t)
```

I noticed this also in `Shallow_water.ipynb` for many of the cases shown.

**Comment by ketch** [comment]
The issue with spikes at t=0 was caused by changes introduced in order to capture near-delta-functions in the pressureless gas chapter.  I've already fixed the issue in https://github.com/clawpack/riemann_book/pull/60, but I haven't merged that in.

The issue with the location of the t pointer has always been there.  I'm not a big fan of the pointer, as it uses up precious space and we already have the horizontal line inside the plot to indicate time.

The changes you've made to this PR look good to me, and if you are finished then I will merge them.  There are a number of spurious changes, which I think are due to the fact that your notebook on whichever machine you used for this is version 2.7.12.  I suggest updating to 2.7.13 just so we have less noise in future commits (no need to modify this PR though, in my opinion).

**Comment by rjleveque** [comment]
Yes, fine to merge now.

I agree we could get rid of the t pointer.

I tried doing a pip upgrade of Jupyter today but it still seems to be stuck at 2.7.12.  Is there something else I need to update?

**Comment by ketch** [comment]
>I agree we could get rid of the t pointer.

Okay, I'll just issue a PR that turns it off by default.

>I tried doing a pip upgrade of Jupyter today but it still seems to be stuck at 2.7.12. Is there something else I need to update?

I'm really not sure what that version refers to, or whether it's really a problem.  But I would go ahead and do

    pip install -U notebook

which will update to Jupyter notebook version 5.0.0, released last week.  They say it doesn't include any backward-incompatible changes and I haven't had problems with it.

**Comment by ketch** [comment]
Oh, actually I just realized that 2.7.x is your Python version, which probably has nothing to do with differences in the notebook (other than the last line, which isn't a big deal).  Upgrading to notebook 5.0.0 may help, though.

**Pull request merged**
